server:
  port: 8080
  servlet:
    context-path: /multi_renter

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/saas_tenant?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=true&serverTimezone=Asia/Shanghai
    username: root
    password: root
    # 驱动是runtime 所以com.mysql.cj.jdbc.Driver报红色是正常的
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 100
      maximum-pool-size: 100
      pool-name: Taroco-Authentication-HikariCP